### ISSUE TITLE
实验结果

### ISSUE THREAD

**Issue by adzhua** [buppt/ChineseNRE#1]
你好，我看了人物关系那个数据集，感觉里面很多数据即使是人都无法直接判断，不知道你的实验结果p，r,f咋样？

**Comment by buppt** [comment]
数据我没有全跑，就用了一小部分，f大概在65％左右，确实有不少关系看不出来，就算噪声吧。。因为我也找不到其他中文数据集了。

**Comment by buppt** [comment]
数据我没有全跑，就用了一小部分，f大概在65％左右，确实有不少关系看不出来，就算噪声吧。。因为我也找不到其他中文数据集了。 @adzhua

**Comment by ufo5** [comment]
有12个类型的的f值吗

**Comment by buppt** [comment]
你跑一下就有了啊
