### ISSUE TITLE
参数问题

### ISSUE THREAD

**Issue by wangyongchao22** [buppt/ChineseNRE#2]
你好，我想请问一下train.py的43，44行中的两个参数POS_SIZE = 82，POS_DIM = 25分别代表什么意思呢？具体是怎么得到的呢？

**Comment by buppt** [comment]
@wangyongchao22  是位置向量的数量和维度，这两个是可以自己调的。

**Comment by wangyongchao22** [comment]
@buppt 嗯呢，不过这里的POS_DIM=25感觉会忽略掉很多的位置信息呢

**Comment by buppt** [comment]
这个我也不确定，可以调一下试试，我一直没有好好调过参。。。
