### ISSUE TITLE
关于位置向量的问题

### ISSUE THREAD

**Issue by zhouyao1124** [buppt/ChineseNRE#3]
你好大神，我是一个纯新手，看到position1.append(i-3-index1)，position2.append(i-3-index2)有些疑惑，这个position1和2是不是表示当前字分别到两个实体的距离？为什么是i-3?而不是直接i-index1?麻烦方便的时候能回复一下，不胜感激。

**Comment by buppt** [comment]
@zhouyao1124 当时好像考虑前三项是实体和关系就减掉了。。。现在看来这里应该是我写错了，多谢指正。

**Comment by zhouyao1124** [comment]
> @zhouyao1124 当时好像考虑前三项是实体和关系就减掉了。。。现在看来这里应该是我写错了，多谢指正。

您客气，我初学知识图谱这块，有很多还不懂，看了您的代码很有帮助，希望您以后多谢博客~再多多跟您讨论~
