### ISSUE TITLE
关于train.py的问题

### ISSUE THREAD

**Issue by zhouyao1124** [buppt/ChineseNRE#4]
您好，我在训练您的模型时，执行train.py代码，会卡住没有反应，请问这种情况您遇到过吗？
![image](https://user-images.githubusercontent.com/37837161/48398030-a10f2f80-e75a-11e8-8640-c9faff360b32.png)

**Comment by buppt** [comment]
卡。。主？是在训练吧，不太清楚你的问题呢。 @zhouyao1124

**Comment by zhouyao1124** [comment]
> 卡。。主？是在训练吧，不太清楚你的问题呢。 @zhouyao1124

额 就是您这个训练完成大概要多久？我设置的BATCH=64,EPOCHS=5，一下午四个多小时，始终是这个界面，没有动过

**Comment by buppt** [comment]
这个还是需要你自己检查一下吧，最简单就打印出来中间的数据看一下，看有没有执行到这一步，一点一点查，虽然训练速度和机器有关，4个小时还是太长了。

**Comment by buppt** [comment]
> > 卡。。主？是在训练吧，不太清楚你的问题呢。 @zhouyao1124
> 
> 额 就是您这个训练完成大概要多久？我设置的BATCH=64,EPOCHS=5，一下午四个多小时，始终是这个界面，没有动过

这个还是需要你自己检查一下吧，最简单就打印出来中间的数据看一下，看有没有执行到这一步，一点一点查，虽然训练速度和机器有关，4个小时还是太长了。
