### ISSUE TITLE
是否可以进行多关系预测呢

### ISSUE THREAD

**Issue by lalalei21** [buppt/ChineseNRE#5]
必须确定了两个实体才能得出位置向量，但通常一句话里不止有2个实体，也不只有一个关系，这种情况下位置向量该怎么得出呢，怎么确定哪两个实体有关系，多关系怎么预测呢。
麻烦您为我解答一下，谢谢

**Comment by buppt** [comment]
> 必须确定了两个实体才能得出位置向量，但通常一句话里不止有2个实体，也不只有一个关系，这种情况下位置向量该怎么得出呢，怎么确定哪两个实体有关系，多关系怎么预测呢。
> 麻烦您为我解答一下，谢谢

想判断哪两个实体的关系，实体的位置向量就以那两个为中心就好了。
